"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from datetime import timedelta
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv("../.env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SUPPORTED_DEPLOY_LOCALES = {"fa", "en"}


def normalize_deploy_locale(value: str | None) -> str:
    raw = (value or "").strip().lower()
    if raw.startswith("en"):
        return "en"
    if raw.startswith("fa"):
        return "fa"
    return "fa"


DEPLOY_LOCALE = normalize_deploy_locale(os.environ.get("APP_LOCALE", "fa"))
if DEPLOY_LOCALE not in SUPPORTED_DEPLOY_LOCALES:
    DEPLOY_LOCALE = "fa"

DEPLOY_DIRECTION_BY_LOCALE = {
    "fa": "rtl",
    # Requirement: English deployment must also be RTL.
    "en": "rtl",
}
DEPLOY_DIRECTION = (os.environ.get("APP_DIRECTION") or DEPLOY_DIRECTION_BY_LOCALE[DEPLOY_LOCALE]).strip().lower()
if DEPLOY_DIRECTION not in {"rtl", "ltr"}:
    DEPLOY_DIRECTION = DEPLOY_DIRECTION_BY_LOCALE[DEPLOY_LOCALE]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"
DEBUG_STORE = os.environ.get("DEBUG_STORE", "True") == "True"
ALLOWED_HOSTS = ["*"]

# When CORS_ALLOW_CREDENTIALS=True, Access-Control-Allow-Origin cannot be *.
# Allow tokan.app + mytoken.ir + all subdomains, and local dev.
# Active store external domains + subdomain origins are handled by DynamicCorsMiddleware (cached).
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://([a-zA-Z0-9-]+\.)*tokan\.app(:\d+)?$",  # tokan.app + *.tokan.app
    r"^https?://([a-zA-Z0-9-]+\.)*mytokan\.ir(:\d+)?$",  # mytoken.ir + *.mytokan.ir
    r"^http://(localhost|127\.0\.0\.1)(:\d+)?$",  # local dev
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8080",
    "http://localhost:3000",
    "https://api.mytokan.ir",
    "https://api.tokan.app"
]


UNFOLD = {
    "SHOW_LANGUAGES": True,
}
# Application definition
INSTALLED_APPS = [
    # "unfold",  # before django.contrib.admin
    # "unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.forms",  # optional, if special form elements are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "ckeditor",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework.authtoken",
    "jwt_auth",
    "drfpasswordless",
    "storages",
    "analytics",
    "link",
    "store",
    "page",
    "meta",
    "slider",
    "menu",
    "media",
    "account",
    "payment",
    "wallet",
    "order",
    "product",
    "reaction",
    "statistic",
    "tag",
    "category",
    "article",
    "drf_yasg",
    "django_filters",
    "import_export",
    "basket",
    "corsheaders",
    "notification",
    "subscription",
    "guide",
    "affiliate",
    "reservation",
    "stream",
    "review",
    "landing",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "range",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-store-host",
]
CORS_ALLOW_CREDENTIALS = True
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.DynamicCorsMiddleware",  # Must be before CorsMiddleware to handle external domains on OPTIONS
    "corsheaders.middleware.CorsMiddleware",  # Must be before CommonMiddleware (django-cors-headers)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "core.middleware.DeploymentLocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.StoreDomainMiddleware",
]

LANGUAGE_CODE = "fa-ir" if DEPLOY_LOCALE == "fa" else "en-us"

USE_I18N = True

LANGUAGES = (
    ("fa", "Persian"),
    ("en", "English"),
)
LOCALE_PATHS = [BASE_DIR / "locale"]
MODULES_CHOICES = (
    ("STORE", "Store"),
    ("BLOG", "Blog"),
)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.deployment_i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Use SQLite if PostgreSQL config is not available
DATABASE_NAME = os.environ.get("DATABASE_NAME")
DATABASE_USER = os.environ.get("DATABASE_USER")
DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD")
DATABASE_HOST = os.environ.get("DATABASE_HOST")
DATABASE_PORT = os.environ.get("DATABASE_PORT")

if DATABASE_NAME and DATABASE_USER and DATABASE_HOST:
    # PostgreSQL configuration is available
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DATABASE_NAME,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
        }
    }
else:
    # Fallback to SQLite
    os.makedirs(BASE_DIR / 'data', exist_ok=True)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'data' / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

TIME_ZONE = "Asia/Tehran"

USE_TZ = True

AUTH_USER_MODEL = "account.User"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "range",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-store-host",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    "SLIDING_TOKEN_LIFETIME": timedelta(days=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=60),
}
# restframework config
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        # "jwt_auth.authentication.StoreJWTAuthentication",
    ],
    # "DEFAULT_PERMISSION_CLASSES": [
    #     "core.permissions.StoreAccessPermission",  # Requires authentication
    # ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "support_request": "5/600",  # 5 per 10 min for landing support form
    },
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=60,
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=180,
    ),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("jwt_auth.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=180),
}
# redis configs
# Use in-memory cache if Redis is not configured
REDIS_URI = os.environ.get('REDIS_URI')
if REDIS_URI:
    # Redis configuration is available
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URI,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'service::cms',
        },
    }
else:
    # Fallback to in-memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

CACHE_TTL = 3 if DEBUG else 60 * 10  # 3 ثانیه در DEBUG، 10 دقیقه در production

# Celery settings
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")


# if not DEBUG:
#     # sentry configure
#     sentry_sdk.init(
#         dsn=os.environ.get('SENTRY_DSN'),
#         # Set traces_sample_rate to 1.0 to capture 100%
#         # of transactions for tracing.
#         traces_sample_rate=1.0,
#         # Set profiles_sample_rate to 1.0 to profile 100%
#         # of sampled transactions.
#         # We recommend adjusting this value in production.
#         profiles_sample_rate=1.0,
#     )


# AWS settings
AWS_ACCESS_KEY_ID = os.environ.get("S3_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("S3_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("S3_STORAGE_BUCKET_NAME")
AWS_DEFAULT_ACL = "public-read"
AWS_S3_CUSTOM_DOMAIN = os.environ.get("S3_CUSTOM_DOMAIN")
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
AWS_S3_ENDPOINT_URL = os.environ.get("S3_ENDPOINT_URL")
AWS_LOCATION = os.environ.get("S3_LOCATION", "")

# وقتی تنظیمات S3 ست نشده باشد، مدیا به‌صورت محلی در MEDIA_ROOT ذخیره می‌شود
USE_S3 = bool(
    AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME
)

STATIC_URL = "/data/static/"
STATIC_ROOT = "data/static/"
STATICFILES_LOCATION = "data/static"
MEDIA_URL = "/data/media/"
MEDIA_ROOT = "data/media/"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ذخیرهٔ مدیا: S3 اگر ست شده باشد، وگرنه دیسک محلی (برای هر دو حالت DEBUG و production)
if USE_S3:
    from .cdn.conf import *

    STORAGES = {
        "default": {
            "BACKEND": "media.storages.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "core.cdn.backends.StaticRootS3BotoStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

if not DEBUG:
    MEDIA_ROOT = "/app/data/media/"


API_URL_BASE = os.environ.get("API_URL_BASE", "https://api.tokan.app")
WEBSITE_URL_BASE = os.environ.get("WEBSITE_URL_BASE", "https://tokan.app")

PASSWORDLESS_AUTH = {
    # Allowed auth types, can be EMAIL, MOBILE, or both.
    "PASSWORDLESS_AUTH_TYPES": ["MOBILE"],
    # URL Prefix for Authentication Endpoints
    "PASSWORDLESS_AUTH_PREFIX": "account/",
    #  URL Prefix for Verification Endpoints
    "PASSWORDLESS_VERIFY_PREFIX": "account/verify/",
    # Amount of time that tokens last, in seconds
    "PASSWORDLESS_TOKEN_EXPIRE_TIME": 5 * 60,
    # The user's email field name
    "PASSWORDLESS_USER_EMAIL_FIELD_NAME": "email",
    # The user's mobile field name
    "PASSWORDLESS_USER_MOBILE_FIELD_NAME": "mobile",
    # Marks itself as verified the first time a user completes auth via token.
    # Automatically unmarks itself if email is changed.
    "PASSWORDLESS_USER_MARK_EMAIL_VERIFIED": False,
    "PASSWORDLESS_USER_EMAIL_VERIFIED_FIELD_NAME": "email_is_verified",
    # Marks itself as verified the first time a user completes auth via token.
    # Automatically unmarks itself if mobile number is changed.
    "PASSWORDLESS_USER_MARK_MOBILE_VERIFIED": False,
    "PASSWORDLESS_USER_MOBILE_VERIFIED_FIELD_NAME": "mobile_is_verified",
    # The email the callback token is sent from
    "PASSWORDLESS_EMAIL_NOREPLY_ADDRESS": None,
    # The email subject
    "PASSWORDLESS_EMAIL_SUBJECT": "Your Login Token",
    # A plaintext email message overridden by the html message. Takes one string.
    "PASSWORDLESS_EMAIL_PLAINTEXT_MESSAGE": "Enter this token to sign in: %s",
    # The email template name.
    "PASSWORDLESS_EMAIL_TOKEN_HTML_TEMPLATE_NAME": "passwordless_default_token_email.html",
    # Your twilio number that sends the callback tokens.
    "PASSWORDLESS_MOBILE_NOREPLY_NUMBER": None,
    # The message sent to mobile users logging in. Takes one string.
    "PASSWORDLESS_MOBILE_MESSAGE": "Use this code to log in: %s",
    # Registers previously unseen aliases as new users.
    "PASSWORDLESS_REGISTER_NEW_USERS": True,
    # Suppresses actual SMS for testing
    "PASSWORDLESS_TEST_SUPPRESSION": False,
    # Context Processors for Email Template
    "PASSWORDLESS_CONTEXT_PROCESSORS": [],
    # The verification email subject
    "PASSWORDLESS_EMAIL_VERIFICATION_SUBJECT": "Your Verification Token",
    # A plaintext verification email message overridden by the html message. Takes one string.
    "PASSWORDLESS_EMAIL_VERIFICATION_PLAINTEXT_MESSAGE": "Enter this verification code: %s",
    # The verification email template name.
    "PASSWORDLESS_EMAIL_VERIFICATION_TOKEN_HTML_TEMPLATE_NAME": "passwordless_default_verification_token_email.html",
    # The message sent to mobile users logging in. Takes one string.
    "PASSWORDLESS_MOBILE_VERIFICATION_MESSAGE": "Enter this verification code: %s",
    # Automatically send verification email or sms when a user changes their alias.
    "PASSWORDLESS_AUTO_SEND_VERIFICATION_TOKEN": False,
    # What function is called to construct an authentication tokens when
    # exchanging a passwordless token for a real user auth token. This function
    # should take a user and return a tuple of two values. The first value is
    # the token itself, the second is a boolean value representating whether
    # the token was newly created.
    "PASSWORDLESS_AUTH_TOKEN_CREATOR": "drfpasswordless.utils.create_authentication_token",
    # What function is called to construct a serializer for drf tokens when
    # exchanging a passwordless token for a real user auth token.
    "PASSWORDLESS_AUTH_TOKEN_SERIALIZER": "drfpasswordless.serializers.TokenResponseSerializer",
    # A dictionary of demo user's primary key mapped to their static pin
    "PASSWORDLESS_DEMO_USERS": {},
    # configurable function for sending email
    "PASSWORDLESS_EMAIL_CALLBACK": "drfpasswordless.utils.send_email_with_callback_token",
    # configurable function for sending sms
    "PASSWORDLESS_SMS_CALLBACK": "helper.sms.verification_sms",
    # Token Generation Retry Count
    "PASSWORDLESS_TOKEN_GENERATION_ATTEMPTS": 3,
}
