user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
  worker_connections 500;
  # multi_accept on;
}

http {
    server {
        listen 80;
        server_name rpmd.ir;

        location /p/ {
            rewrite ^/p/(.*)$ https://ropomoda.com/product/rp-$1 permanent;
            rewrite ^/p/(.*)/(.*)$ https://ropomoda.com/product/rp-$1/$2 permanent;
        }
        location /u/ {
            rewrite ^/u/(.*)$ https://ropomoda.com/order/orp-$1 permanent;
        }
        location / {
            return 301 https://ropomoda.com$request_uri;
        }
    }
    server {
        listen 80;
        server_name pay.rpmd.ir;

        location / {
            proxy_pass https://tokan-backend.darkube.app/v1/wallet/transaction/payment/verify;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    server {
        listen 80;
        server_name ropomoda.com;

        location / {
            proxy_pass http://ropofront.ropomoda.svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
        server {
        listen 80;
        server_name staging.ropomoda.com;

        location / {
            proxy_pass http://ropofront.ropomoda.svc:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
     server {
        listen 80;
        server_name api.staging.ropomoda.com;

        location / {
            proxy_pass http://ropoapi.ropomoda.svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
         server {
        listen 80;
        server_name api.ropomoda.com;

        location / {
            proxy_pass http://ropoapi.ropomoda.svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
