# Generated by Django 4.2.7 on 2025-08-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_is_deleted_media_owner'),
        ('category', '0004_alter_category_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
