# Generated by Django 5.0.6 on 2025-10-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_icon_category_is_editable_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_icon',
            field=models.CharField(blank=True, choices=[('electronics', 'الکترونیک'), ('clothing', 'پوشاک'), ('home', 'خانه و آشپزخانه'), ('food', 'غذا و نوشیدنی'), ('sports', 'ورزش و سرگرمی'), ('books', 'کتاب و لوازم تحریر'), ('beauty', 'زیبایی و سلامت'), ('automotive', 'خودرو و موتورسیکلت'), ('toys', 'اسباب بازی'), ('health', 'سلامت و پزشکی')], help_text='آیکون پیش\u200cفرض انتخاب شده', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_type',
            field=models.CharField(choices=[('default', 'آیکون پیش\u200cفرض'), ('uploaded', 'آیکون آپلود شده')], default='default', help_text='نوع آیکون: پیش\u200cفرض یا آپلود شده', max_length=50),
        ),
    ]
