# Generated by Django 5.0.6 on 2025-10-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_default_icon_category_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_icon',
            field=models.CharField(blank=True, choices=[('smartphone', 'موبایل'), ('laptop', 'لپ\u200cتاپ'), ('headphones', 'هدفون'), ('camera', 'دوربین'), ('tablet', 'تبلت'), ('monitor', 'مانیتور'), ('speaker', 'بلندگو'), ('keyboard', 'کیبورد'), ('mouse', 'ماوس'), ('router', 'روتر'), ('printer', 'پرینتر'), ('harddrive', 'هارد'), ('memory', 'رم'), ('cpu', 'پردازنده'), ('gpu', 'کارت گرافیک'), ('webcam', 'وب\u200cکم'), ('microphone', 'میکروفون'), ('gamepad', 'گیم\u200cپد'), ('vr', 'واقعیت مجازی'), ('drone', 'پهپاد'), ('shirt', 'پیراهن'), ('dress', 'لباس'), ('shoe', 'کفش'), ('watch', 'ساعت'), ('hat', 'کلاه'), ('glasses', 'عینک'), ('belt', 'کمربند'), ('bag', 'کیف'), ('scarf', 'شال'), ('glove', 'دستکش'), ('tie', 'کراوات'), ('sock', 'جوراب'), ('underwear', 'زیرپوش'), ('jacket', 'ژاکت'), ('pants', 'شلوار'), ('skirt', 'دامن'), ('swimsuit', 'لباس شنا'), ('jewelry', 'جواهرات'), ('ring', 'انگشتر'), ('necklace', 'گردنبند'), ('earring', 'گوشواره'), ('bracelet', 'دستبند'), ('default', 'پیش\u200cفرض')], help_text='آیکون پیش\u200cفرض انتخاب شده', max_length=50, null=True),
        ),
    ]
