# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_default_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_color',
            field=models.CharField(blank=True, help_text='رنگ آیکون (hex مثلا #3B82F6) - برای آیکون پیش\u200cفرض', max_length=20, null=True),
        ),
    ]
