# Generated by Django 5.1.4 on 2025-06-12 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_payment_link_and_more'),
        ('wallet', '0002_alter_transaction_store_alter_wallet_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('purchase', 'Purchase'), ('card_to_card', 'Card to Card'), ('gift', 'Gift')], max_length=20),
        ),
    ]
