# Generated by Django 5.1.4 on 2025-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_order_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_online_pruchase',
            field=models.BooleanField(default=False),
        ),
    ]
