# Generated by Django 5.1.4 on 2025-07-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_created_at_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='gift_expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
