# Generated by Django 5.1.4 on 2025-07-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_store_slogan'),
        ('wallet', '0006_wallet_gift_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
