# Generated by Django 5.1.4 on 2025-07-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_address_store_alter_storeuser_store'),
        ('wallet', '0007_alter_transaction_store_alter_wallet_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.storeuser'),
        ),
    ]
