# Generated by Django 5.1.4 on 2025-08-09 20:04

import wallet.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_transaction_wallet_remove_wallet_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_online_pruchase',
            new_name='has_online_payment',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='total_balance',
            new_name='withdrawable_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=wallet.models.TransactionTypeField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction'), ('inner transfer', 'Inner Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=wallet.models.TransactionStatusField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
