# Generated by Django 5.1.4 on 2025-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rename_is_online_pruchase_transaction_has_online_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_gift',
            new_name='has_gift',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='withdrawable_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
