# Generated by Django 5.1.4 on 2025-08-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_rename_is_gift_transaction_has_gift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='store',
        ),
    ]
