# Generated by Django 5.1.4 on 2025-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_remove_transaction_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='has_gift',
        ),
    ]
