# Generated by Django 5.1.4 on 2025-08-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_remove_transaction_has_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_total_withdrawable', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_gift', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_blocked', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_purchased', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_inner_transfered', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_withdrawed', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_to_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recorded_total_gift_used', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
