# Generated by Django 4.2.7 on 2025-08-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_systemaccountant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
