# Generated by Django 5.1.4 on 2025-07-04 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slider', 'index']},
        ),
        migrations.AddField(
            model_name='slide',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slider.slider'),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('slider', 'index')},
        ),
    ]
