# Generated by Django 5.1.4 on 2025-07-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_alter_slide_options_slide_index_alter_slide_slider_and_more'),
        ('store', '0014_alter_store_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
