# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slider", "0003_alter_slide_store_alter_slider_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="button_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="slide",
            name="show_button",
            field=models.BooleanField(default=True),
        ),
    ]
