# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slider", "0004_slide_button_text_slide_show_button"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="component",
        ),
    ]
