# Generated by Django 5.1.4 on 2025-07-14 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_alter_address_store_alter_storeuser_store'),
        ('product', '0007_alter_color_store_alter_product_store_and_more'),
        ('store', '0014_alter_store_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rating_aggregated_value', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.storeuser')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reaction.reaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.storeuser')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reaction.reaction')),
            ],
            options={
                'unique_together': {('reaction', 'store_user')},
            },
        ),
    ]
