# Generated by Django 5.1.4 on 2026-03-02

import uuid
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "تعطیلی عمومی",
                "verbose_name_plural": "تعطیلات عمومی",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.store")),
            ],
            options={
                "verbose_name": "دسته‌بندی خدمات",
                "verbose_name_plural": "دسته‌بندی‌های خدمات",
                "ordering": ["sort_order", "title"],
                "unique_together": {("store", "title")},
            },
        ),
        migrations.CreateModel(
            name="ReservationSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("timezone", models.CharField(default="Asia/Tehran", max_length=64)),
                (
                    "slot_interval_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[MinValueValidator(5), MaxValueValidator(240)],
                    ),
                ),
                (
                    "booking_window_days",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[MinValueValidator(1), MaxValueValidator(365)],
                    ),
                ),
                (
                    "min_advance_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[MinValueValidator(0), MaxValueValidator(43200)],
                    ),
                ),
                ("use_public_holidays", models.BooleanField(default=False)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.store")),
            ],
            options={
                "verbose_name": "تنظیمات رزرواسیون",
                "verbose_name_plural": "تنظیمات رزرواسیون",
            },
        ),
        migrations.CreateModel(
            name="ProviderWorkingHour",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "دوشنبه"),
                            (1, "سه‌شنبه"),
                            (2, "چهارشنبه"),
                            (3, "پنجشنبه"),
                            (4, "جمعه"),
                            (5, "شنبه"),
                            (6, "یکشنبه"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_capacity", models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="reservation.serviceprovider",
                    ),
                ),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.store")),
            ],
            options={
                "verbose_name": "ساعت کاری ارائه‌دهنده",
                "verbose_name_plural": "ساعات کاری ارائه‌دهندگان",
                "ordering": ["provider", "weekday", "start_time"],
                "unique_together": {("provider", "weekday", "start_time", "end_time")},
            },
        ),
        migrations.CreateModel(
            name="ProviderTimeOff",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("is_full_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_offs",
                        to="reservation.serviceprovider",
                    ),
                ),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.store")),
            ],
            options={
                "verbose_name": "تعطیلی ارائه‌دهنده",
                "verbose_name_plural": "تعطیلات ارائه‌دهندگان",
                "ordering": ["date", "start_time"],
                "unique_together": {("provider", "date", "start_time", "end_time")},
            },
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="reservation.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="مدت زمان سرویس به دقیقه",
                validators=[MinValueValidator(5), MaxValueValidator(720)],
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "verbose_name": "بازه زمانی",
                "verbose_name_plural": "بازه‌های زمانی",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="reservationsetting",
            constraint=models.UniqueConstraint(fields=("store",), name="uniq_reservation_setting_per_store"),
        ),
    ]
