# Generated by Django 5.1.4 on 2025-06-26 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_fullname', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.TextField()),
                ('postcode', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('frequently_used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
