# Generated by Django 5.1.4 on 2025-06-26 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address'),
        ('meta', '0001_initial'),
        ('store', '0003_alter_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.province'),
        ),
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.ForeignKey(default='c950229c-1205-4e2a-8cf0-91e06ddfa153', on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
