# Generated by Django 5.1.4 on 2025-07-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_address_city_address_province_address_store_and_more'),
        ('store', '0004_rename_fa_title_store_title_store_favicon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('store', 'mobile')},
        ),
    ]
