# Generated by Django 5.1.4 on 2025-07-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_options_alter_user_unique_together_and_more'),
        ('store', '0014_alter_store_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
