# Generated by Django 5.1.4 on 2025-08-13 18:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_address_store_alter_storeuser_store'),
        ('store', '0019_alter_store_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(blank=True, max_length=26, validators=[django.core.validators.RegexValidator('^IR\\d{24}$', 'شماره شبا باید با IR شروع شود و ۲۴ رقم بعدی عدد باشد.')], verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'شماره کارت باید ۱۶ رقم باشد.')], verbose_name='شماره کارت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
