# Generated by Django 4.2.7 on 2025-08-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
