# Generated by Django 5.1.4

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_remove_storeuser_national_id_user_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageGuide",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("path", models.CharField(help_text="مسیر صفحه داشبورد مثلاً /dashboard یا /dashboard/pages", max_length=500, unique=True)),
                ("video_desktop", models.URLField(blank=True, help_text="لینک ویدیو راهنما برای حالت دسکتاپ", max_length=1000, null=True)),
                ("video_mobile", models.URLField(blank=True, help_text="لینک ویدیو راهنما برای حالت موبایل", max_length=1000, null=True)),
                ("description", models.TextField(blank=True, help_text="توضیحات متنی راهنما", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "راهنمای صفحه",
                "verbose_name_plural": "راهنماهای صفحات",
                "ordering": ["path"],
            },
        ),
    ]
