# Generated by Django 5.0.1 on 2026-02-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_storeadminpermission_media_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='کد لینک دعوت افیلیت'),
        ),
    ]
