# Generated by Django 5.1.4 on 2025-01-28 01:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fa_title', models.CharField(max_length=300)),
                ('en_title', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
