# Generated by Django 5.1.4 on 2025-01-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
