# Generated by Django 5.1.4 on 2025-07-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_created_at_media_updated_at'),
        ('store', '0003_alter_store_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='fa_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='store',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_favicons', to='media.media'),
        ),
        migrations.AddField(
            model_name='store',
            name='full_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_full_logos', to='media.media'),
        ),
        migrations.AddField(
            model_name='store',
            name='minimal_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_minimal_logos', to='media.media'),
        ),
    ]
