# Generated by Django 5.1.4 on 2025-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_fa_title_store_title_store_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gift_color',
            field=models.CharField(default='#80d', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#000', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
