# Generated by Django 5.1.4 on 2025-07-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_bale_url_store_eitaa_url_store_enamad_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#2c2', max_length=10),
        ),
    ]
