# Generated by Django 5.1.4 on 2025-07-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_store_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slogan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
