# Generated by Django 5.1.4 on 2025-07-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_slogan_alter_store_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='gift_color',
            field=models.CharField(default='#8800dd', max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#22cc22', max_length=10),
        ),
    ]
