# Generated by Django 5.1.4 on 2025-07-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_store_gift_color_alter_store_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'پلن رایگان'), (1, 'پلن 1'), (2, 'پلن 2'), (3, 'پلن 3')], default=0),
        ),
    ]
