# Generated by Django 5.1.4 on 2025-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_store_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_super_store',
            field=models.BooleanField(default=False),
        ),
    ]
