# Generated by Django 5.1.4 on 2025-07-10 18:52

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_is_super_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('level', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('color', 'Color'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('url', 'URL'), ('text', 'Text')], max_length=20)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('can_edit_by_store', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='store',
            old_name='is_super_store',
            new_name='_is_super_store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bale_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='store',
            name='eitaa_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='enamad_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='gift_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='level',
        ),
        migrations.RemoveField(
            model_name='store',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='rubika_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='samandehi_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='store',
            name='_dns_record_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='_jwt_secret',
            field=models.CharField(default=secrets.token_urlsafe, max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='external_domain',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='super_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='store_super_store', to='store.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='store_plan', to='store.plan'),
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.settingdefinition')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='store.store')),
            ],
            options={
                'unique_together': {('store', 'definition')},
            },
        ),
    ]
