# Generated by Django 5.1.4 on 2025-07-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_list_images_alter_product_code'),
        ('store', '0012_plan_settingdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plan_product', to='product.product'),
        ),
    ]
