# Generated by Django 5.1.4 on 2025-07-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_plan_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slogan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
