# Generated by Django 5.1.4 on 2025-07-14 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_store_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingdefinition',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='store_plan', to='store.plan'),
        ),
    ]
