# Generated by Django 5.1.4 on 2025-07-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_color_store_alter_product_store_and_more'),
        ('store', '0015_settingdefinition_temp_id_storesetting_temp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='is_accepted',
            new_name='is_banned',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plan_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
