# Generated by Django 5.1.4 on 2025-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_is_accepted_store_is_banned_plan_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='en_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
