# Generated by Django 5.1.4 on 2025-07-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_store_en_title_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_shared_store',
            field=models.BooleanField(default=True),
        ),
    ]
