# Generated by Django 5.1.4 on 2025-08-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_store_is_shared_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
