# Generated by Django 5.1.4 on 2025-08-13 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_is_deleted_media_owner'),
        ('store', '0019_alter_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_multi_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(default='---', max_length=300),
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='store_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='store_category', to='store.storecategory'),
        ),
    ]
