# Generated by Django 4.2.7 on 2025-08-16 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_store_is_multi_vendor_alter_plan_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='product',
        ),
        migrations.AddField(
            model_name='plan',
            name='shared_paymnent_percentage',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='store',
            name='gift_percentage',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='store',
            name='has_gift',
            field=models.BooleanField(default=False),
        ),
    ]
