# Generated by Django 5.0.6 on 2025-10-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_plan_product_plan_shared_paymnent_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Color Name')),
                ('hex_code', models.CharField(help_text='e.g., #FF0000', max_length=7, verbose_name='Hex Code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store Color',
                'verbose_name_plural': 'Store Colors',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StoreSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Size Name')),
                ('size_type', models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('general', 'General')], default='general', max_length=20, verbose_name='Size Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store Size',
                'verbose_name_plural': 'Store Sizes',
                'ordering': ['order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
