# Generated by Django 5.0.6 on 2025-10-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_stock_alter_variant_color_alter_variant_size'),
        ('store', '0022_storecolor_storesize'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storesize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storesize',
            name='store',
        ),
        migrations.DeleteModel(
            name='StoreColor',
        ),
        migrations.DeleteModel(
            name='StoreSize',
        ),
    ]
