# Generated by Django 5.0.1 on 2026-02-20 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0029_unique_super_store_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="store",
            name="unique_super_store",
        ),
    ]
