# Generated by Django 5.0.1 on 2026-02-27 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0026_shippingmethod_is_active_tracking_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='درصد کمیسیون پیش\u200cفرض')),
                ('default_duration_months', models.PositiveIntegerField(default=12, verbose_name='مدت اعتبار کمیسیون (ماه)')),
            ],
            options={
                'verbose_name': 'تنظیمات افیلیت',
                'verbose_name_plural': 'تنظیمات افیلیت',
            },
        ),
        migrations.CreateModel(
            name='AffiliateInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد کمیسیون (خالی = پیش\u200cفرض)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار کمیسیون')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_invited_by', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دعوت افیلیت',
                'verbose_name_plural': 'دعوت\u200cهای افیلیت',
                'ordering': ['-created_at'],
                'unique_together': {('inviter', 'invitee')},
            },
        ),
        migrations.CreateModel(
            name='AffiliateEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ خرید')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ کمیسیون')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد اعمال\u200cشده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'واریز شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_earnings', to='order.order')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='affiliate.affiliateinvite')),
            ],
            options={
                'verbose_name': 'کمیسیون افیلیت',
                'verbose_name_plural': 'کمیسیون\u200cهای افیلیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualAffiliateCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False, verbose_name='واریز به کیف پول')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affiliate_credits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_affiliate_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کمیسیون دستی افیلیت',
                'verbose_name_plural': 'کمیسیون\u200cهای دستی افیلیت',
                'ordering': ['-created_at'],
            },
        ),
    ]
