# Generated by Django 5.0.1 on 2026-02-13 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0016_pageguide"),
        ("store", "0023_alter_storesize_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreNotificationManager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("available_sms_count", models.IntegerField(default=0)),
                ("available_email_count", models.IntegerField(default=0)),
                ("available_push_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_sms", models.BooleanField(default=False)),
                ("is_email", models.BooleanField(default=False)),
                ("is_push", models.BooleanField(default=False)),
                ("issued", models.BooleanField(default=False)),
                ("scheduled_to", models.DateTimeField(null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="store.store"
                    ),
                ),
                (
                    "store_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.storeuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField(blank=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعات"),
                            ("warning", "هشدار"),
                            ("success", "موفقیت"),
                            ("announcement", "اعلان"),
                        ],
                        default="announcement",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "پنل ادمین"),
                            ("system", "سیستم"),
                            ("order", "سفارش"),
                            ("product", "محصول"),
                            ("blog", "بلاگ"),
                            ("user", "کاربر"),
                            ("other", "سایر"),
                        ],
                        default="admin",
                        max_length=50,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="لینک اختیاری", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="خالی = همه فروشگاه\u200cها",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان سیستمی",
                "verbose_name_plural": "اعلانات سیستمی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemAnnouncementRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="notification.systemannouncement",
                    ),
                ),
                (
                    "store_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_reads",
                        to="account.storeuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "خوانده شدن اعلان",
                "verbose_name_plural": "خوانده شدن اعلانات",
                "unique_together": {("announcement", "store_user")},
            },
        ),
    ]
