# Generated by Django 5.1.4 on 2025-06-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_created_at_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='external_transaction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_to_card', 'Card to Card'), ('online', 'Online Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
