# Generated by Django 5.1.4 on 2025-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_external_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wallet_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
