# Generated by Django 5.1.4 on 2025-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_payment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paied', 'Paied'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
