# Generated by Django 5.1.4 on 2025-06-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_is_payed_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_to_card', 'Card to Card'), ('online', 'Online Payment')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
