# Generated by Django 5.1.4 on 2025-06-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_payment_link_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wallet_amount',
        ),
    ]
