# Generated by Django 5.1.4 on 2025-07-03 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_created_at_media_updated_at'),
        ('meta', '0002_city_province'),
        ('order', '0013_order_delivery_address_order_delivery_amount'),
        ('store', '0003_alter_store_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='payable_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tracking_code',
            new_name='shipping_tracking_code',
        ),
        migrations.AddField(
            model_name='order',
            name='products_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shipping_payment_on_delivery', models.BooleanField(default=False)),
                ('product_payment_on_delivery', models.BooleanField(default=False)),
                ('max_payment_on_delivery', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('base_shipping_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_price_per_extra_kilograms', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tracking_code_base_url', models.CharField(max_length=500)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='media.media')),
                ('store', models.ForeignKey(default='c950229c-1205-4e2a-8cf0-91e06ddfa153', on_delete=django.db.models.deletion.PROTECT, to='store.store')),
                ('supported_cities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='meta.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='order.shippingmethod'),
        ),
    ]
