# Generated by Django 5.1.4 on 2025-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_rename_total_amount_order_payable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
