# Generated by Django 5.1.4 on 2025-07-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_city_province'),
        ('order', '0015_alter_shippingmethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='supported_cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='meta.city'),
        ),
    ]
