# Generated by Django 5.1.4 on 2025-07-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_options_alter_user_unique_together_and_more'),
        ('order', '0017_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.storeuser'),
        ),
    ]
