# Generated by Django 5.1.4 on 2025-08-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_store_alter_orderitem_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
