# Generated by Django 5.1.4 on 2025-08-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_user'),
        ('wallet', '0010_rename_is_gift_transaction_has_gift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='wallet.transaction'),
        ),
    ]
