# Generated by Django 4.2.7 on 2025-08-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_orderitem_product_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
