# Generated by Django 5.0.1 on 2026-02-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_shippingmethoddefinition_and_definition_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_methods",
                to="order.shippingmethoddefinition",
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethoddefinition",
            name="default_max_payment_on_delivery",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=20, null=True
            ),
        ),
    ]
