# Generated by Django 5.1.4 on 2025-07-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='store',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='province',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='province',
            name='store',
        ),
        migrations.RemoveField(
            model_name='province',
            name='updated_at',
        ),
    ]
