# Generated by Django 5.1.4 on 2025-01-28 01:51

import django.db.models.deletion
import media.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(storage=media.storages.MediaStorage(), upload_to='media/')),
                ('file_type', models.CharField(blank=True, default='unknown', max_length=50)),
                ('file_size', models.PositiveBigIntegerField(blank=True, default=0)),
                ('hash_sum', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=300)),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
