# Generated by Django 5.1.4 on 2025-07-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_created_at_media_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='domain',
            field=models.CharField(blank=True, default='storage.tokan.app', max_length=100),
        ),
    ]
