# Generated by Django 5.0.1 on 2026-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0006_media_is_deleted_media_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(upload_to="media/"),
        ),
    ]
