# Generated by Django 5.1.4 on 2025-07-10 22:29

import link.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=1000)),
                ('short_code', models.CharField(default=link.models.generate_short_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
