# Generated by Django 5.1.4 on 2025-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
