# Generated by Django 5.1.4 on 2025-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_created_at_media_updated_at'),
        ('product', '0005_color_created_at_color_updated_at_size_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_images_product', to='media.media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
