# Generated by Django 4.2.7 on 2025-08-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_icon_category_is_editable_category_slug'),
        ('media', '0006_media_is_deleted_media_owner'),
        ('product', '0008_alter_product_category_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_accepted_to_dsiaply_on_super_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_images',
            field=models.ManyToManyField(blank=True, related_name='list_images_product', to='media.media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_main_image', to='media.media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_variant_product', to='product.variant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='list_images',
            field=models.ManyToManyField(blank=True, related_name='list_images_variant', to='media.media'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product'),
        ),
    ]
