# Generated by Django 5.0.6 on 2026-01-27

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_alter_storesize_unique_together_and_more"),
        ("product", "0011_product_stock_alter_variant_color_alter_variant_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantAttribute",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "display_type",
                    models.CharField(
                        choices=[("color", "Color"), ("text", "Text"), ("number", "Number")],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("legacy_color", "Legacy Color"),
                            ("legacy_size", "Legacy Size"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.store"),
                ),
            ],
            options={"unique_together": {("store", "slug")}},
        ),
        migrations.CreateModel(
            name="VariantAttributeValue",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="product.variantattribute",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.store"),
                ),
            ],
            options={"ordering": ["sort_order", "title"], "unique_together": {("store", "attribute", "title")}},
        ),
        migrations.AddField(
            model_name="variant",
            name="extra_attribute_values",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]

