# Generated by Django 5.0.6 on 2026-01-27

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_variant_attributes_and_extra_attributes"),
    ]

    operations = [
        # Remove legacy fields from Variant
        migrations.RemoveField(
            model_name="variant",
            name="color",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="size",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="extra_attribute_values",
        ),
        # Remove legacy-oriented field from VariantAttribute
        migrations.RemoveField(
            model_name="variantattribute",
            name="source",
        ),
        # Drop legacy models
        migrations.DeleteModel(
            name="Color",
        ),
        migrations.DeleteModel(
            name="Size",
        ),
        # Add through model for Variant ↔ AttributeValue
        migrations.CreateModel(
            name="VariantAttributeSelection",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="product.variantattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="product.variantattributevalue",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_selections",
                        to="product.variant",
                    ),
                ),
            ],
            options={"unique_together": {("variant", "attribute")}},
        ),
        migrations.AddField(
            model_name="variant",
            name="attribute_values",
            field=models.ManyToManyField(
                blank=True,
                related_name="variants",
                through="product.VariantAttributeSelection",
                to="product.variantattributevalue",
            ),
        ),
    ]

