# Generated by Django 5.0.6

from django.db import migrations, models


def migrate_category_to_categories(apps, schema_editor):
    """Migrate existing category FK to categories M2M, including all ancestors."""
    Product = apps.get_model("product", "Product")
    Category = apps.get_model("category", "Category")
    for product in Product.objects.select_related("category").filter(category__isnull=False):
        cat = product.category
        # Get category + all ancestors (root first, then down to cat)
        ids = []
        c = cat
        while c:
            ids.insert(0, c.id)
            c = c.parent
        product.categories.set(ids)


def reverse_migrate(apps, schema_editor):
    """Set category to one category from categories (for rollback)."""
    Product = apps.get_model("product", "Product")
    for product in Product.objects.prefetch_related("categories"):
        cats = list(product.categories.all())
        if cats:
            product.category_id = cats[-1].id
            product.save(update_fields=["category_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_product_tags"),
        ("category", "0007_alter_category_default_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="category.Category",
            ),
        ),
        migrations.RunPython(migrate_category_to_categories, reverse_migrate),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
