# Generated by Django

from django.db import migrations, models


def migrate_downloadable_file_to_files(apps, schema_editor):
    """تبدیل downloadable_file قدیمی به downloadable_files"""
    Product = apps.get_model("product", "Product")
    for p in Product.objects.filter(downloadable_file_id__isnull=False):
        if not p.downloadable_files:
            p.downloadable_files = [
                {"media_id": str(p.downloadable_file_id), "title": "", "description": ""}
            ]
            p.save(update_fields=["downloadable_files"])


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_product_digital_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="downloadable_files",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='آرایه فایل‌ها: [{"media_id":"uuid","title":"","description":""}]',
            ),
        ),
        migrations.RunPython(migrate_downloadable_file_to_files, migrations.RunPython.noop),
    ]
