# Generated by Django 5.1.4 on 2025-01-28 18:18

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_store'),
        ('media', '0002_alter_media_store'),
        ('store', '0002_alter_store_domain'),
        ('tag', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300, null='')),
                ('slug', models.SlugField(blank=True, max_length=70, null='', unique=True)),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(blank=True, choices=[('index', 'Index'), ('noindex', 'No-Index'), ('follow', 'Follow'), ('nofollow', 'No-Follow')], max_length=100, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('total_views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('main_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_main_image', to='media.media')),
                ('store', models.ForeignKey(default='c950229c-1205-4e2a-8cf0-91e06ddfa153', on_delete=django.db.models.deletion.PROTECT, to='store.store')),
                ('tags', models.ManyToManyField(null=True, to='tag.tag')),
                ('thumbnail_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'managed': True,
                'indexes': [models.Index(fields=['module', 'slug'], name='article_art_module_7c6f09_idx'), models.Index(fields=['module', 'title'], name='article_art_module_245da5_idx'), models.Index(fields=['module', 'category'], name='article_art_module_bcf740_idx'), models.Index(fields=['module', 'category', 'created_at'], name='article_art_module_e59067_idx'), models.Index(fields=['module', 'category', 'title'], name='article_art_module_94446c_idx')],
            },
        ),
    ]
