# Generated by Django 5.1.4 on 2025-07-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('store', '0014_alter_store_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
