# Generated by Django 5.0.1 on 2026-01-31 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0007_alter_category_default_icon"),
        ("page", "0003_remove_widget_is_layout_widgettype_is_layout"),
        ("product", "0013_remove_legacy_color_size_and_add_selection"),
        ("store", "0023_alter_storesize_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        help_text="Unique key for fetching menu (e.g. header, footer).",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Only one primary menu is allowed per store.",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="store.store"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("empty", "Empty"),
                            ("category", "Category"),
                            ("product", "Product"),
                            ("page", "Page"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=1000, null=True)),
                ("index", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="category.category",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menu",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="page.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="product.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="store.store"
                    ),
                ),
            ],
            options={
                "ordering": ["menu", "parent_id", "index"],
            },
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("key__isnull", False), models.Q(("key", ""), _negated=True)
                ),
                fields=("store", "key"),
                name="unique_menu_key_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("store",),
                name="unique_primary_menu_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.UniqueConstraint(
                fields=("menu", "parent", "index"),
                name="unique_menu_item_index_per_parent",
            ),
        ),
    ]
