# Generated by Django 5.1.4 on 2025-01-28 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_alter_media_store'),
        ('store', '0002_alter_store_domain'),
        ('wallet', '0002_alter_transaction_store_alter_wallet_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('configuration', models.JSONField()),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('store', models.ForeignKey(default='c950229c-1205-4e2a-8cf0-91e06ddfa153', on_delete=django.db.models.deletion.PROTECT, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_link', models.CharField(max_length=300)),
                ('authority', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20)),
                ('is_payed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(default='c950229c-1205-4e2a-8cf0-91e06ddfa153', on_delete=django.db.models.deletion.PROTECT, to='store.store')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentgateway')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
