# Generated by Django 5.1.4 on 2025-08-09 20:04

import django.db.models.deletion
import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_media_store'),
        ('payment', '0003_alter_payment_store_alter_paymentgateway_store'),
        ('wallet', '0009_rename_is_online_pruchase_transaction_has_online_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='documentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_documentry', to='media.media'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=payment.models.PaymentTypeField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], default='withdrawal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentgateway'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=payment.models.PaymentStatusField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
