# Generated by Django 5.1.4 on 2025-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_documentary_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_online_payment',
            field=models.BooleanField(default=True),
        ),
    ]
