# Generated by Django 5.0.1 on 2026-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_paymentgatewaytype_has_sandbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgatewaytype",
            name="has_sandbox",
            field=models.BooleanField(default=False),
        ),
    ]
