# Generated by Django 5.0.1 on 2026-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0011_paymentgateway_logo_null_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
