# Generated by Django 5.0.1 on 2026-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widgettype",
            name="theme",
        ),
    ]
