# Generated by Django 5.0.1 on 2026-01-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0002_remove_widgettype_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="is_layout",
        ),
        migrations.AddField(
            model_name="widgettype",
            name="is_layout",
            field=models.BooleanField(
                default=False, help_text="آیا این ویجت، layout صفحه است؟"
            ),
        ),
    ]
