# Generated by Django 5.0.1 on 2026-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_remove_widget_is_layout_widgettype_is_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="widget_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="تنظیمات ویجت به صورت JSON"
            ),
        ),
    ]
