# Generated by Django 5.0.1 on 2026-02-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0005_page_path_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="path",
            field=models.CharField(
                help_text="مسیر ثابت مثل / یا /about - یا خالی اگر path_pattern استفاده شود",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="path_pattern",
            field=models.CharField(
                blank=True,
                help_text="الگوی مسیر داینامیک. مثال: /product/:id:number/:slug?:string (id اجباری عددی، slug اختیاری رشته)",
                max_length=500,
                null=True,
            ),
        ),
    ]
