# Generated by Django 5.0.1 on 2026-02-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0007_unify_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgettype",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widget_types",
                to="page.theme",
            ),
        ),
    ]
